---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      batch: demo
  template:
    metadata:
      labels:
        batch: demo
    spec:
      containers:
      - name: vote
        image: codingbaba/c51:vote
        resources:
          requests:
            memory: "300Mi"
            cpu: ".3"
          limits:
            memory: "500Mi"
            cpu: ".5"

---

apiVersion: v1
kind: Service
metadata:
  name: vote
spec: 
  type: LoadBalancer
  selector:
    batch: demo
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      batch: redis
  template:
    metadata:
      labels:
        batch: redis
    spec:
      containers:
      - name: redis
        image: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec: 
  type: ClusterIP
  selector:
    batch: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work
spec:
  replicas: 2
  selector:
    matchLabels:
      batch: work
  template:
    metadata:
      labels:
        batch: work
    spec:
      containers:
      - name: work
        image: codingbaba/c51:work

---
apiVersion: v1
kind: Service
metadata:
  name: work
spec: 
  type: ClusterIP
  selector:
    batch: work
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      batch: db
  template:
    metadata:
      labels:
        batch: db
    spec:
      containers:
      - image: postgres:15-alpine
        name: db
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres 

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec: 
  type: ClusterIP
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    batch: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 2
  selector:
    matchLabels:
      batch: result
  template:
    metadata:
      labels:
        batch: result
    spec:
      containers:
      - name: result
        image: codingbaba/c51:results
        ports:
        - containerPort: 4000  # Optional, but recommended for clarity
        resources:
          requests:
            memory: "300Mi"
            cpu: ".3"
          limits:
            memory: "500Mi"
            cpu: ".5"

---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  selector:
    batch: result
  ports:
  - port: 80        # External port (you will access the app on this port)
    targetPort: 4000  # Port inside the container (where the app is running)
