---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: result
  template:
    metadata:
      labels:
        batch: result
    spec:
      containers:
      - name: result
        image: codingbaba/c51:results
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: db
        resources:
          requests:
            memory: "300Mi"
            cpu: ".3"
          limits:
            memory: "500Mi"
            cpu: ".5"

---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  selector:
    batch: result
  ports:
  - port: 80
    targetPort: 4000
