---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: demo
  template:
    metadata:
      labels:
        batch: demo
    spec:
      containers:
      - name: vote
        image: codingbaba/c51:vote
        resources:
          requests:
            memory: "300Mi"
            cpu: ".3"
          limits:
            memory: "500Mi"
            cpu: ".5"
        env:
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: LoadBalancer
  selector:
    batch: demo
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: redis
  template:
    metadata:
      labels:
        batch: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    batch: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: work
  template:
    metadata:
      labels:
        batch: work
    spec:
      containers:
      - name: work
        image: codingbaba/c51:work
        env:
        - name: DB_HOST
          value: db

---
apiVersion: v1
kind: Service
metadata:
  name: work
spec:
  type: ClusterIP
  selector:
    batch: work
 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: db
  template:
    metadata:
      labels:
        batch: db
    spec:
      containers:
      - image: postgres:15-alpine
        name: db
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    batch: db
  ports:
  - name: db
    port: 5432
    targetPort: 5432
